export default {
  getStarted: {
    welcomeToKokua: 'Welcome to Kokua',
    intro: 'Help when you need it most.',
    intro2: 'Disbursements for Disaster Relief.',
    getStartedButton: 'Get started',
    getVerified: 'Please verify identity',
    tos: "By continuing, you agree to Kokua's {{Terms of Service}} and acknowledge you've read our {{Privacy Policy}}",
    tosTitle: 'Terms of Service',
    tosText:
      'Your free (non-paid) access to and use of the websites (the "Sites") and mobile apps for any service offered by Kokua (collectively, the "Services") is subject to you agreeing to these general terms of service (the "General Terms"). If you do not agree to these general terms, then you may not access or use the Kokua Services.',
    tosText2:
      'By clicking "I understand" (or words to similar effect), registering for a Kokua account, or otherwise using any of our Services, you agree to be legally bound by these General Terms, and agree that Kokua may make changes to these General Terms on a going-forward basis at any time in its sole discretion, as described further below.',
    privacyPolicyTitle: 'Privacy Policy',
    privacyPolicyText:
      'When you sign up for or use the Kokua app, you give us certain information voluntarily.',
    privacyPolicyText2:
      'Kokua is committed to protecting your privacy. This Privacy Policy explains our policy regarding the collection, use, disclosure, processing and transfer of certain information, including your personal information by Kokua.',
    acknowledgeButton: 'I understand',
  },
  kyc: {
    headline: 'Verify your identity and apply for support.',
    subtitle:
      'Verify your identity to see what support is available around you now.',
    verifyNowButton: 'Verify Now',
    skipButton: 'Skip for now',
  },
  auth: {
    createAccount: 'Create account',
  },
  discover: {
    verifyIdentity: {
      title: 'Verify identity',
      applySupport: 'Verify your Identity and apply for support',
      applySupportIsAvailableAround:
        'Verify your Identity to see what support is available around you now',
      greeting: 'Hello',
      verificationPending: 'Verification pending',
      wait: 'Please wait',
      moreInfo: 'Information required',
    },
    verifyYourIdentity: 'Verify your Identity',
    pleaseVerifyYourIdentity: 'Please verify your identity',
    aroundYou: 'Around you',
    weCantFindAnySupportsAroundYou: 'We can’t find any supports around you',
    organizations: 'Organizations',
    viewAll: 'View all',
    caruselAroundContentTitleFirst: 'Hurricane Disaster',
    caruselAroundContentTitleSecond: 'Relief',
    carusel: {
      first: 'Help Oklahoma',
      second: 'Help Oklahoma',
    },
    skipForNow: 'Skip for now',
    discover: 'Discover',
    wallet: 'Wallet',
    identity: 'Identity',
    applySupportTextContent:
      'Your free (non-paid) access to and use of the websites (the "Sites") and mobile apps for any service offered by Kokua (collectively, the "Services") is subject to you agreeing to these general terms of service (the "General Terms"). If you do not agree to these general terms, then you may not access or use the Kokua Services. \n\nBy clicking "I understand" (or words to similar effect), registering for a Kokua account, or otherwise using any of our Services, you agree to be legally bound by these General Terms, and agree that Kokua may make changes to these General Terms on a going-forward basis at any time in its sole discretion, as described further below.',
    fundsSupport: 'Funds Support',
    prepaidDigitalCard: 'Prepaid Digital Card',
    sweetBox: 'Sweet Box',
    supportProvideYou: 'This support will provide you',
    acceptKokua: 'I accept the Kokua',
    shareYourDdetails: 'Share your details',
    additionalDetails: 'Additional Details',
    describeSituation: 'Describe Situation',
    next: 'Next',
    applicationForm: 'Application Form',
    shareYourDetailsScreenText:
      'Kokua is committed to protect your privacy. We delete the data collected in this context after its storage is no longer neccessary, or we limit its processing where it is subject to legal obligations to regaining data',
    shareDetailsSecondScreenText:
      "Enter the amount of support in $ of assistance's that you have already recieved from the other agencies",
    shareDetailsThirdText: 'Please enter number of family members',
    shareDetailsFourthText:
      'Enter how much of each specific item of this bundle you will need. Please be fair, every request will be filtered by an administrator and you application may be rejected',
    socialSecurityNumber: 'Social Security Number',
    address: 'Address',
    FEMANumber: 'FEMA Number',
    SBA: 'SBA',
    privateInsurance: 'Private Insurance',
    otherAssistance: 'Other Assistance',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    description: 'Description',
    uploadVideoFromGallery: 'Upload video from gallery',
    recordVideo: 'Record Video',
    gotIt: 'Got It',
    thankYouprovidingInfo:
      'Thank your for providing your information. We will verify your identity within the next 24 hours and send you a notification about the result.',
    applicationSubmitted: 'Application Submitted',
    yourRequestMayTake: 'Your request may take up to 1 day',
    nameSurname: 'Name Surname',
    householdIncome: 'Household Income',
    typeOfStructure: 'Type of Structure',
    ownership: 'Ownership',
    referringAgency: 'Referring Agency',
    adults: 'Adults',
    children: 'Children',
    clothing: 'Clothing',
    food: 'Food',
    housing: 'Housing',
  },
  validation: {
    stringRequired: 'A string is required',
    numberRequired: 'A number is required',
    socialSecurityNumberRequired: 'Social Security Number is Required',
    pleaseValidEmail: 'Please enter valid email',
    emailAddressRequired: 'Email Address is Required',
    phoneNumberRequired: 'Phone number is Required',
    phoneNumberInvalid: 'It doeesn`t look like phone number',
    adressRequired: 'Address is Required',
    fullNameRequired: 'Your name and surname is Required',
    FEMANumberRequired: 'FEMA Number is Required',
    householdIncome: 'Household Income is Required',
    typeOfStructure: 'Type of Structure is Required',
    ownership: 'Ownership is Required',
    referringAgency: 'Referring Agency is Required',
    SBA: 'SBA is Required',
    privateInsurance: 'Private Insurance is Required',
    otherAssistance: 'Other Assistance is Required',
    adults: 'Adults count is Required',
    children: 'Children count is Required',
    clothing: 'Clothing count is Required',
    food: 'Food count is Required',
    housing: 'Housing count is Required',
  },
  applications: {
    pageTitle: 'Support Applications',
    tabs: {
      all: 'All',
      accepted: 'Accepted',
      rejected: 'Rejected',
      pending: 'Pending',
    },
    applicationStatus: {
      Accepted: 'Accepted',
      Rejected: 'Rejected',
      Pending: 'Pending',
    },
    applyAgain: 'Apply Again',
    listOfGoods: 'List of goods you have been supported with.',
    deliveryStatus: 'Status',
    noApplicationsFound: "You don't have any{{filter}}applications yet",
    filterAccepted: ' accepted ',
    filterRejected: ' rejected ',
    filterPending: ' pending ',
  },
  identity: {
    verifyHeadline: 'Verify your onchain account',
    verifyBody: 'in 3 easy steps',
    emailHeadline: 'Verify email',
    emailBody: 'Please verify your email',
    phoneHeadline: 'Verify phone number',
    phoneBody: 'Please verify your phone number',
    kycHeadline: 'KYC process',
    kycBody: 'Please verify your KYC',
    verified: 'Verified',
    pending: 'Pending',
  },
};
